## #1 Import Libraries

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

## #2 Generate Dummy Data

In [2]:
# Generate 100 random data points
np.random.seed(42) # for reproducity
X = np.random.rand(100, 2)

# Define the labels based on a simple classification rule
y = (X[:,0] + X[:, 1] > 1).astype(int)

y

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [4]:
X[:10]

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258],
       [0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914]])

## #3 Build Binary Classifier

In [5]:
class BinaryClassifier(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(BinaryClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc_out = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.fc2(out)
        out = self.relu(out)
        out = self.fc_out(out)
        out = self.sigmoid(out)
        
        return out

## #4 Instantiate Binary Classifier

In [69]:
model = BinaryClassifier(input_size=2, hidden_size=5, output_size=1)
preds = model(torch.Tensor(X))
preds[0]

tensor([0.5164], grad_fn=<SelectBackward0>)

**Define Criterion and Optimizer**

In [70]:
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

**Define accuracy function**

In [71]:
def binary_accuracy(preds, y):
    """ 
        Returns accruacy per batch i.e. 
        if you get 8/10 right, this returns 0.8
    """
    
    # round predictions to the closest integer
    rounded_preds = torch.round(torch.sigmoid(preds))
    correct = (rounded_preds == y).float()
    acc = correct.sum() / len(correct)
    return acc

## #5 Create training loop

In [73]:
epochs = 1000

for epoch in range(epochs):
    # Convert data to PyTorch tensor
    inputs = torch.Tensor(X)
    
    # reshape labels from single row to single column
    labels = torch.Tensor(y).reshape(-1, 1)
    
    # zero the gradients
    optimizer.zero_grad()
    
    # Forward pass
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    acc = binary_accuracy(outputs, labels)
    
    # backward pass and optimizer
    loss.backward() # computes gradients with respect to model parameters
    
    # use gradient to update weights and biases
    optimizer.step()
    
    # print progress
    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}, Accuracy: {acc.item()*100:.2f}%")

Epoch [10/1000], Loss: 0.0454, Accuracy: 58.00%
Epoch [20/1000], Loss: 0.0451, Accuracy: 58.00%
Epoch [30/1000], Loss: 0.0449, Accuracy: 58.00%
Epoch [40/1000], Loss: 0.0446, Accuracy: 58.00%
Epoch [50/1000], Loss: 0.0443, Accuracy: 58.00%
Epoch [60/1000], Loss: 0.0441, Accuracy: 58.00%
Epoch [70/1000], Loss: 0.0438, Accuracy: 59.00%
Epoch [80/1000], Loss: 0.0436, Accuracy: 60.00%
Epoch [90/1000], Loss: 0.0433, Accuracy: 60.00%
Epoch [100/1000], Loss: 0.0431, Accuracy: 60.00%
Epoch [110/1000], Loss: 0.0429, Accuracy: 60.00%
Epoch [120/1000], Loss: 0.0426, Accuracy: 60.00%
Epoch [130/1000], Loss: 0.0424, Accuracy: 60.00%
Epoch [140/1000], Loss: 0.0422, Accuracy: 60.00%
Epoch [150/1000], Loss: 0.0420, Accuracy: 60.00%
Epoch [160/1000], Loss: 0.0417, Accuracy: 60.00%
Epoch [170/1000], Loss: 0.0415, Accuracy: 60.00%
Epoch [180/1000], Loss: 0.0413, Accuracy: 60.00%
Epoch [190/1000], Loss: 0.0411, Accuracy: 60.00%
Epoch [200/1000], Loss: 0.0409, Accuracy: 60.00%
Epoch [210/1000], Loss: 0.040