In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Generate 100 random data points
np.random.seed(42)
X = np.random.rand(100, 2)

# Define the labels based on a simple classification rule
y = (X[:, 0] + X[:, 1] > 1).astype(int)

y

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [39]:
X[0, 0] + X[0, 1]

1.3252544252572787

**Build Binary Classifier**

In [17]:
class BinaryClassifier(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(BinaryClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc_out = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.fc2(out)
        out = self.relu(out)
        out = self.fc_out(out)
        out = self.sigmoid(out)
        
        return out

**Instantiate Binary Classifier**

In [20]:
model = BinaryClassifier(input_size=2, hidden_size=5, output_size=1)
preds = model(torch.Tensor(X))
preds[:5]

tensor([[0.4077],
        [0.3956],
        [0.4028],
        [0.4137],
        [0.3998]], grad_fn=<SliceBackward0>)

In [21]:
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [32]:
def binary_accuracy(preds, y):
    """ 
        Returns accruacy per batch i.e. 
        if you get 8/10 right, this returns 0.8
    """
    
    # round predictions to the closest integer
    rounded_preds = torch.round(torch.sigmoid(preds))
    correct = (rounded_preds == y).float()
    acc = correct.sum() / len(correct)
    return acc

In [41]:
y

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [35]:
epochs = 1000

for epoch in range(epochs):
    # Convert data to PyTorch tensors
    inputs = torch.Tensor(X)
    # reshapes labels from single row to single column
    labels = torch.Tensor(y).reshape(-1, 1)
    
    # Forward pass
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    acc = binary_accuracy(outputs, labels)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    # Print progress
    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}, Accuracy: {acc.item()*100:.2f}%")

Epoch [10/1000], Loss: 0.0223, Accuracy: 87.00%
Epoch [20/1000], Loss: 0.0223, Accuracy: 87.00%
Epoch [30/1000], Loss: 0.0223, Accuracy: 87.00%
Epoch [40/1000], Loss: 0.0223, Accuracy: 87.00%
Epoch [50/1000], Loss: 0.0223, Accuracy: 87.00%
Epoch [60/1000], Loss: 0.0222, Accuracy: 87.00%
Epoch [70/1000], Loss: 0.0222, Accuracy: 87.00%
Epoch [80/1000], Loss: 0.0222, Accuracy: 87.00%
Epoch [90/1000], Loss: 0.0222, Accuracy: 87.00%
Epoch [100/1000], Loss: 0.0221, Accuracy: 87.00%
Epoch [110/1000], Loss: 0.0221, Accuracy: 87.00%
Epoch [120/1000], Loss: 0.0221, Accuracy: 87.00%
Epoch [130/1000], Loss: 0.0221, Accuracy: 87.00%
Epoch [140/1000], Loss: 0.0221, Accuracy: 87.00%
Epoch [150/1000], Loss: 0.0220, Accuracy: 87.00%
Epoch [160/1000], Loss: 0.0220, Accuracy: 87.00%
Epoch [170/1000], Loss: 0.0220, Accuracy: 87.00%
Epoch [180/1000], Loss: 0.0220, Accuracy: 87.00%
Epoch [190/1000], Loss: 0.0219, Accuracy: 87.00%
Epoch [200/1000], Loss: 0.0219, Accuracy: 87.00%
Epoch [210/1000], Loss: 0.021

In [37]:
# Generate new test data
X_test = np.random.rand(10, 2)

# Convert data to PyTorch tensor
inputs = torch.Tensor(X_test)

# Make predictions
preds = model(inputs)
preds = (preds > 0.5).int()

print("Predictions: ", preds.squeeze().tolist())

Predictions:  [1, 1, 0, 1, 1, 0, 1, 0, 1, 0]
