# Advanced Tensor Operations

* Advanced Matrix Operations
* Tensor Products
* Tensor Decomposition

## Advanced Matrix Operations

* Matrix Inversion
* Matrix Trace
* Matrix Determinant

**Matrix Inversion**

In [2]:
import torch

In [5]:
a = torch.tensor([[4, 3, 2],
                  [5, 1, 2],
                  [1, 3, 6]], dtype=torch.float32)

a_inv = torch.inverse(a)

print(a_inv)

print(a @ a_inv)

tensor([[ 0.0000,  0.2143, -0.0714],
        [ 0.5000, -0.3929, -0.0357],
        [-0.2500,  0.1607,  0.1964]])
tensor([[1.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0000e+00, 0.0000e+00],
        [0.0000e+00, 5.9605e-08, 1.0000e+00]])


A^-1 = A|I_3

**Perform Gaussian Elimination to get inverse**

`[4, 3, 2 | [1, 0, 0
  5, 1, 2 |  0, 1, 0
  1, 3, 6 |  0, 0, 1]`
  
`[4, 3, 2 | [1, 0, 0
  5, 1, 2 |  0, 1, 0
  0, 10,20|  0, 5, -5]`
  
**Inverse of a 3x3 Matrix** 
https://www.youtube.com/watch?v=Fg7_mv3izR0


**Matrix Trace**


In [7]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Method1
trace1 = a.trace()
print(trace1)

# method
trace2 = torch.trace(a)
print(trace2)

tensor(15)
tensor(15)


**Matrix Determinant**

If a matrix has a zero determinant, then it does not have an inverse, otherwise if the matrix has a nonzero determinant, then it has an inverse.

In [9]:
a = torch.tensor([[1, 2, 3],
                  [3, 4, 5],
                  [5, 6, 7]], dtype=torch.float32)

a_det = torch.det(a)

print(a_det)

tensor(0.)


In [13]:
a = torch.tensor([[7, -4, 2],
                  [3, 1, -5],
                  [2, 2, -5]], dtype=torch.float32)

a_det = torch.det(a)

print(a_det)

tensor(23.0000)


`[a, b
  c, d]` ad - bc
  
7([1, -5, 
   2, -5]) - -4([3, -5, 
                 2, -5]) + 2([3, 1, 
                              2, 2])
                              
7(-5 + 10) - -4(-15 + 10) + 2(6 - 2)
7(5) - -4(-5) + 2(4)
35 -20 + 8
15 + 8 = 23

## Tensor Products

**Inner/Dot Product**

In [14]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

inner_product = torch.dot(x, y)

print(inner_product)

tensor(32)


**Outer Product**

In [15]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

outer_product = torch.ger(x, y)

print(outer_product)

tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])


**Hadamard Product**

In [16]:
x = torch.tensor([[2, 3, 4], [5, 6, 7]])
y = torch.tensor([[2, 4, 6], [6, 10, 12]])

z = torch.mul(x, y)

print(z)

tensor([[ 4, 12, 24],
        [30, 60, 84]])


**Kronecker Product**

In [17]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[0, 5], [6, 7]])

c = torch.kron(a, b)

print(c)

tensor([[ 0,  5,  0, 10],
        [ 6,  7, 12, 14],
        [ 0, 15,  0, 20],
        [18, 21, 24, 28]])


**Tensor Contraction**

In [18]:
a = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]])
b = torch.tensor([[7, 8], [9, 10], [11, 12]])

# contract on the first dim
# first-left, first-right
c = torch.einsum('ik,kj->ij', a, b)
print(c)

# contract on the second dim
# first-left, first-mid, first-right
c = torch.einsum('ik,kj->ij', b, a)
print(c)

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 39,  54,  69],
        [ 49,  68,  87],
        [ 59,  82, 105]])


139

## Tensor Decomposition

* Singular Value Decomposition (SVD)
* Eigenvalue Decomposition (EVD)

**Singular Value Decomposition**

In [23]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype=torch.float32)

U, S, V = torch.svd(a)

print("U: ", U)
print("S: ", S)
print("V: ", V)

a_reconstructed = torch.mm(U, torch.mm(torch.diag(S), V.t()))

print(a_reconstructed)

U:  tensor([[-0.2148,  0.8872,  0.4082],
        [-0.5206,  0.2496, -0.8165],
        [-0.8263, -0.3879,  0.4082]])
S:  tensor([1.6848e+01, 1.0684e+00, 2.3721e-07])
V:  tensor([[-0.4797, -0.7767, -0.4082],
        [-0.5724, -0.0757,  0.8165],
        [-0.6651,  0.6253, -0.4082]])
tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.0000],
        [7.0000, 8.0000, 9.0000]])


$$A = \cup\Sigma\vee^T$$

**Eigenvalue Decomposition**

In [24]:
a = torch.tensor([[1,2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype=torch.float32)

eigenvalues, eigenvectors = torch.linalg.eig(a)

a_reconstructed = eigenvectors @ torch.diag_embed(eigenvalues) @ torch.inverse(eigenvectors)

print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)

print("Original Matrix: ", a)
print("Reconstructed Matrix: ", a_reconstructed)

Eigenvalues:  tensor([ 1.6117e+01+0.j, -1.1168e+00+0.j, -1.2253e-07+0.j])
Eigenvectors:  tensor([[-0.2320+0.j, -0.7858+0.j,  0.4082+0.j],
        [-0.5253+0.j, -0.0868+0.j, -0.8165+0.j],
        [-0.8187+0.j,  0.6123+0.j,  0.4082+0.j]])
Original Matrix:  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Reconstructed Matrix:  tensor([[1.0000+0.j, 2.0000+0.j, 3.0000+0.j],
        [4.0000+0.j, 5.0000+0.j, 6.0000+0.j],
        [7.0000+0.j, 8.0000+0.j, 9.0000+0.j]])
