In [2]:
import torch
import numpy as np

In [3]:
scalar = torch.tensor(5)
print(scalar)

tensor(5)


In [4]:
scalar.dtype

torch.int64

In [5]:
vector = torch.tensor([1, 2, 3, 4, 5])

vector

tensor([1, 2, 3, 4, 5])

In [6]:
matrix = torch.tensor([[2, 3, 3],
                       [4, 5, 6]])

matrix

tensor([[2, 3, 3],
        [4, 5, 6]])

In [7]:
matrix.shape

torch.Size([2, 3])

In [8]:
array = np.random.rand(3, 3)
array

array([[0.0770598 , 0.78918774, 0.26540484],
       [0.41527631, 0.66315621, 0.84193169],
       [0.79628033, 0.92509534, 0.3471476 ]])

In [9]:
tensor = torch.from_numpy(array)
tensor

tensor([[0.0771, 0.7892, 0.2654],
        [0.4153, 0.6632, 0.8419],
        [0.7963, 0.9251, 0.3471]], dtype=torch.float64)

In [10]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
random  = torch.rand(3, 4)
random

tensor([[0.7007, 0.1463, 0.3803, 0.1465],
        [0.4420, 0.0047, 0.9835, 0.0914],
        [0.1838, 0.3036, 0.6883, 0.3664]])

In [13]:
random.shape

torch.Size([3, 4])

In [14]:
random.dtype

torch.float32