In [1]:
import torch

## Element-wise Operations

**Element-wise Addition**

In [2]:
x = torch.tensor([4, 3, 2])
y = torch.tensor([5, 1, 2])

z = x + y # element-wise addition
z2 = torch.add(x, y) # same operation
print(z)
print(z2)

tensor([9, 4, 4])
tensor([9, 4, 4])


**Element-wise Subtraction**

In [3]:
x = torch.tensor([[4, 5], [6, 7], [6, 3]])
y = torch.tensor([[5, 2], [1, 2], [4, 2]])

z = x - y
z2 = torch.subtract(x, y)

print(z)
print(z2)

tensor([[-1,  3],
        [ 5,  5],
        [ 2,  1]])
tensor([[-1,  3],
        [ 5,  5],
        [ 2,  1]])


**Element-wise Multiplication**

In [4]:
x = torch.tensor([5, 6, 1])
y = torch.tensor([1, 2, 3])

z = x * y
z2 = torch.multiply(x, y)

print(z)
print(z2)

tensor([ 5, 12,  3])
tensor([ 5, 12,  3])


**Element-wise Division**

In [5]:
x = torch.tensor([[5, 6, 1], [5, 3, 1]])
y = torch.tensor([[1, 2, 3], [7, 8, 9]])

z = x / y
z2 = torch.divide(x, y)

print(z)
print(z2)

tensor([[5.0000, 3.0000, 0.3333],
        [0.7143, 0.3750, 0.1111]])
tensor([[5.0000, 3.0000, 0.3333],
        [0.7143, 0.3750, 0.1111]])


## Broadcasting Tensors

In [6]:
a = torch.tensor([[1, 2], [3, 4]])

b = 2

c = a + b
print(c)

tensor([[3, 4],
        [5, 6]])


In [7]:
a = torch.tensor([[4, 5, 5], [6, 7, 8], [1, 2, 3]])

b = 5

print(a * b)

tensor([[20, 25, 25],
        [30, 35, 40],
        [ 5, 10, 15]])


In [9]:
a = torch.tensor([[5, 3, 1], [6, 7, 8], [9, 0, 2]])
b = torch.tensor([6, 7, 2])

print(a * b)

tensor([[30, 21,  2],
        [36, 49, 16],
        [54,  0,  4]])


In [12]:
a = torch.tensor([[6, 4, 2], [6, 4, 2]])
b = torch.tensor([5, 6, 7])

print(a / b)

tensor([[1.2000, 0.6667, 0.2857],
        [1.2000, 0.6667, 0.2857]])


## Matrix Multiplication and Dot Product

In [17]:
# Matrix Multiplication
a = torch.tensor([[4, 5, 6], [6, 1, 2], [12, 13, 5]])
b = torch.tensor([[4, 5, 6], [2, 1, 3]])
b = b.t()

c = torch.matmul(a, b)
c2 = torch.mm(a, b)
c3 = a @ b

print(c)
print(c2)
print(c3)

tensor([[ 77,  31],
        [ 41,  19],
        [143,  52]])
tensor([[ 77,  31],
        [ 41,  19],
        [143,  52]])
tensor([[ 77,  31],
        [ 41,  19],
        [143,  52]])


In [18]:
print(b)

tensor([[4, 2],
        [5, 1],
        [6, 3]])


In [28]:
# Dot product
a = torch.tensor([4, 5, 1])
b = torch.tensor([1, 2, 3])

c = torch.dot(a, b)
print(c)

tensor(17)


## Reduction Operations

**Sum**

In [29]:
a = torch.tensor([[1, 2], [5, 6]])

a = torch.sum(a)

print(a)

tensor(14)


In [31]:
a = torch.tensor([[1, 2], [4, 5]])

z = a.sum()
print(z)

z = a.sum(dim=0)
print(z)

z = a.sum(dim=1)
print(z)

tensor(12)
tensor([5, 7])
tensor([3, 9])


**Mean**

In [34]:
a = torch.tensor([[4, 1], [5, 6]], dtype=torch.float32)

z = torch.mean(a)
print(z)

z = torch.mean(a, dim=0)
print(z)

z = torch.mean(a, dim=1)
print(z)

tensor(4.)
tensor([4.5000, 3.5000])
tensor([2.5000, 5.5000])


**Max**

In [35]:
a = torch.tensor([[4, 1], [5, 6]], dtype=torch.float32)

z = torch.max(a)
print(z)

z = torch.max(a, dim=0)
print(z)

z = torch.max(a, dim=1)
print(z)

tensor(6.)
torch.return_types.max(
values=tensor([5., 6.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([4., 6.]),
indices=tensor([0, 1]))


**Min**

In [36]:
a = torch.tensor([[4, 1], [5, 6]], dtype=torch.float32)

z = torch.min(a)
print(z)

z = torch.min(a, dim=0)
print(z)

z = torch.min(a, dim=1)
print(z)

tensor(1.)
torch.return_types.min(
values=tensor([4., 1.]),
indices=tensor([0, 0]))
torch.return_types.min(
values=tensor([1., 5.]),
indices=tensor([1, 0]))
